# Generated by Django 4.2.7 on 2023-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255, verbose_name='Book_Name')),
                ('book_number', models.IntegerField(verbose_name='Book_Number')),
                ('chapter', models.IntegerField(verbose_name='Chapter')),
                ('verse', models.IntegerField(verbose_name='Verse')),
                ('Text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
